/**
 * Generated API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Site } from './site';
import { Address } from './address';
import { UserRole } from './userRole';


export interface User { 
    address?: Address;
    employeeId?: string;
    firstName?: string;
    id?: string;
    lastName?: string;
    personalId?: string;
    site?: Site;
    supervisor?: User;
    userRoles?: Set<UserRole>;
}

